package problems

import utils.PolygonalNumbers
import utils.Strings
import java.io.File
import kotlin.math.sqrt

fun main() {
    Problem044().run()
}

/**
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8.
 * However, their difference, 70 − 22 = 48, is not pentagonal.
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and
 * D = |Pk − Pj| is minimised; what is the value of D?
 */
class Problem044: Problem() {
    override suspend fun solve(): Long {
        var k = 7
        do {
            for (j in k - 1 downTo 1) {
                val p_k = PolygonalNumbers.nthPentagonal(k)
                val p_j = PolygonalNumbers.nthPentagonal(j)
                val sum = p_k + p_j
                val diff = p_k - p_j
                println("j, k = ($j, $k), P_j = $p_j, P_k = $p_k, P_k + P_j = $sum, D = $diff")
                if (PolygonalNumbers.isPentagonal(sum) && PolygonalNumbers.isPentagonal(diff)) {
                    return diff
                }
            }
            k++
        } while (true)
        return -1L
    }
}